# Generated by Django 3.1.7 on 2021-09-12 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210312_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_list',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
