# Generated by Django 3.1.7 on 2021-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_active_list_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='total_bid',
            field=models.IntegerField(default=0),
        ),
    ]
