# Generated by Django 3.1.7 on 2021-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210913_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='placed_on',
        ),
        migrations.AddField(
            model_name='bids',
            name='placed_on',
            field=models.ManyToManyField(related_name='bids', to='auctions.active_list'),
        ),
    ]
