# Generated by Django 3.1.7 on 2021-09-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210915_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='placed_on',
        ),
        migrations.AddField(
            model_name='bids',
            name='placed_on',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.active_list'),
            preserve_default=False,
        ),
    ]
